dist: bionic
sudo: true
language: cpp
os: linux

addons:
  sonarcloud:
    organization: "jmramosr-github"
  apt:
    packages:
      - g++
      - gcc
      - make
      - lcov
      - gcovr
      - doxygen

before_install:
  - pip install codecov
  - pip install gcovr

cache:
  apt: true
  directories:
  - "${TRAVIS_BUILD_DIR}/deps/doxygen"
  - '$HOME/.sonar/cache'

script:
  - cmake -DCMAKE_BUILD_TYPE=ON -DCOVERAGE=1 -DBUILD_TESTS=ON .
  - build-wrapper-linux-x86-64 --out-dir bw-output make generate_gcovr
  - bash generate_gcov.sh
  - sonar-scanner -Dsonar.cfamily.build-wrapper-output=bw-output

after_success:
  - codecov -t $CODECOV_TOKEN -X gcov
