dist: trusty
sudo: true
language: cpp

addons:
  sonarcloud:
    organization: "jmramosr_TravisCppCmakeExample"
  apt:
    sources:
      - deadsnakes
    packages:
      - python3.5
      - g++
      - gcc
      - make
      - lcov
      - gcovr
      - doxygen

cache:
  apt: true
  directories:
  - "${TRAVIS_BUILD_DIR}/deps/doxygen"
  - '$HOME/.sonar/cache'

before_install:
  - pip install --upgrade pip
  - pip install --user cpp-coveralls
  - pip install codecov
  - pip install gcovr

script:
  - cmake -DCMAKE_BUILD_TYPE=ON -DCOVERAGE=1 -DBUILD_TESTS=ON .
  - build-wrapper-linux-x86-64 --out-dir bw-output make all
  - ./runUnitTests
  - bash generate_gcov.sh
  - sonar-scanner -Dsonar.cfamily.build-wrapper-output=bw-output

after_success:
  - coveralls -t $COVERALLS_TOKEN --root . --gcov "./gcov/" -n -E ".*CMakeFiles.*"
  - codecov -t $CODECOV_TOKEN -X gcov
