dist: bionic
sudo: true
language: cpp

addons:
  sonarcloud:
    organization: "jmramosr_TravisCppCmakeExample"
  apt:
    sources:
      - deadsnakes
    packages:
      - python3.5
      - g++
      - gcc
      - make
      - lcov
      - gcovr
      - doxygen

cache:
  apt: true
  directories:
  - "${TRAVIS_BUILD_DIR}/deps/doxygen"
  - '$HOME/.sonar/cache'

script:
  - cmake -DCOVERAGE=1 -DBUILD_TESTS=ON .
  - build-wrapper-linux-x86-64 --out-dir bw-output cmake --build . 
  - ./runUnitTests
  - bash generate_gcov.sh
  - sonar-scanner -Dsonar.projectKey=jmramosr_TravisCppCmakeExample -Dsonar.sources=./src,./include -Dsonar.organization=jmramosr-github -Dsonar.cfamily.gcov.reportsPath=./gcov/ -Dsonar.cfamily.coverage.reportPath=./coverage/coverage.xml -Dsonar.exclusions= -Dsonar.cfamily.build-wrapper-output=bw-output -Dsonar.cfamily.threads=8

after_success:
  - coveralls --root . --gcov ./gcov/ -E ".*CMakeFiles.*" 
  - codecov -t $CODECOV_TOKEN -X gcov
