dist: trusty
sudo: false
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-5.0
    packages:
      - g++
      - clang
      - valgrind
      - lcov

before_install:
  - pip install --user cpp-coveralls
  - pip install codecov
  - pip install gcovr

script:
  - CXX=/usr/bin/g++-6 CC=/usr/bin/gcc-6 cmake -DCOVERAGE=1 .
  - cmake --build . 
  - ./tests
  - gcovr -r ./ --xml -o ./coverage.xml

after_success:
  - coveralls --root . -E ".*CMakeFiles.*" 
  - codecov -t $CODECOV_TOKEN -X gcov
