dist: bionic
sudo: true
language: cpp

addons:
  sonarcloud:
    organization: "jmramosr_TravisCppCmakeExample"
  apt:
    sources:
      - deadsnakes
    packages:
      - python3.5
      - g++
      - gcc
      - make
      - clang
      - valgrind
      - lcov
      - gcovr
      - doxygen

cache:
  apt: true
  directories:
  - "${TRAVIS_BUILD_DIR}/deps/doxygen"

before_install:
  - pip install --upgrade pip
  - pip install --user cpp-coveralls
  - pip install codecov
  - pip install gcovr

script:
  - cmake -DCOVERAGE=1 .
  - cmake --build . 
  - ./project1
  - gcovr -r ./ --xml -o ./coverage.xml
  - ls -la
  - sonar-scanner -Dsonar.projectKey=jmramosr_TravisCppCmakeExample -Dsonar.sources=./src,./include -Dsonar.organization=jmramosr-github -Dsonar.cfamily.coverage.reportPath=coverage.xml -Dsonar.exclusions=

after_success:
  - coveralls --root . -E ".*CMakeFiles.*" 
  - codecov -t $CODECOV_TOKEN -X gcov
